<?php

// Variaveis globais
//$_ENV VARIAVEIS DO AMBIENTE
//$_GET PARAMETROS QUE FORAM ENVIADO POR REQUEST GET
//$_POST PARAMETROS ENVIADOS POR POST
//$_COOKIE VALORES DE COOKIES
//$_SERVER INFORMAÇÇOES DO SERVIDOR
//$_FILES INFORMAÇÕES SOBRE OS ARQUIVOS QUE VIERAM POR UPLOAD





?>